name: camparat_game
description: Camparat Game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0

flutter:
  assets:
    - assets/images/
