name: camparat_game
description: Camparat Game
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.18.0
  shared_preferences: ^2.3.2

flutter:
  assets:
    - assets/images/
  fonts:
    - family: PPGatwick
      fonts:
        - asset: fonts/PPGatwick-Ultralight.woff
        - asset: fonts/PPGatwick-Bold.woff
          weight: 700
